name: "Update branch for hotfix or release"

inputs:
  release_type:
    description: "Release or hotfix"
    required: true
  base_branch:
    description: "Base branch for hotfix or release PR"
    required: true
  release_version:
    description: "Release or hotfix version"
    required: true

description: Create Release PR
runs:
  using: "composite"
  steps:
    - name: Create hotfix branch
      run: |
        git fetch origin ${{ inputs.base_branch }}
        git checkout ${{ inputs.base_branch }}
        git checkout -b ${{ inputs.release_type }}/${{ inputs.release_version }}
      shell: bash
    
    # In order to make a commit, we need to initialize a user.
    # You may choose to write something less generic here if you want, it doesn't matter functionality wise.
    - name: Initialize mandatory git config
      run: |
        git config --global user.email "bot@backbase.com"
        git config --global user.name "Release BOT"
      shell: bash

    # In this step we need to update release version
    - name: YQ - bump version on production
      uses: mikefarah/yq@v4.2.1
      with:
        cmd: "yq e '
        .configurations[\"prod\"].version_name = \"${{ inputs.release_version }}\" |
        .configurations[\"stg\"].version_name = \"${{ inputs.release_version }}\" 
        ' -i fastlane/props.yaml"
        
    - name: Write to CHANGELOG.md
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: CHANGELOG.md
        contents: |
          echo "${{ github.event.issue.body }}"
        write-mode: overwrite

    - name: Update CHANGELOG.md
      uses: thomaseizinger/keep-a-changelog-new-release@1.1.0
      with:
        version: ${{ inputs.release_version }}

    - name: Commit changelog and manifest files
      id: make-commit
      run: |
        git add .
        git commit --message "Prepare ${{ inputs.release_type }} ${{ inputs.release_version }}"
        echo "::set-output name=commit::$(git rev-parse HEAD)"
      shell: bash

    - name: Push new branch
      run: |
          git fetch
          git push origin ${{ inputs.release_type }}/${{ inputs.release_version }}
      shell: bash