name: "Deploy Prod build"

#
#   IMPORTANT TO KNOW
# - This workflow runs every time there are changes to `develop` branch.
#
on:
  push:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CACHE_BUNDLER: ~/.bundler

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 90

    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}

        run: |
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > $SIGNING_KEY_STORE_PATH

      - name: Build and publish DEV app with Fastlane
        uses: ./.github/actions/fastlane
        with:
          lane_name: "master"
          conf_env: "prod"
          APP_SIGN_KEY_ALIAS: ${{ secrets.RELEASE_APP_SIGN_KEY_ALIAS }}
          APP_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_APP_SIGN_KEY_PASSWORD }}
          APP_SIGN_STORE_PASSWORD: ${{ secrets.RELEASE_APP_SIGN_STORE_PASSWORD }}
          APP_SIGN_KEYSTORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
          sonar_token:             ${{ secrets.SONAR_TOKEN }}

          github_run_id: ${{ env.GITHUB_RUN_ID }}
          app_version_code: ${{ github.run_number }}


      - name: Upload App
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: App bundle
          path: app/build/outputs/bundle/prodRelease/
