name: SonarCloud analysis
on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
    types: [ opened, synchronize, reopened ]

env:
  APP_SIGN_KEYSTORE_PATH: /tmp/keystore
  CACHE_BUNDLER: ~/.bundler
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Write key file
        env:
          AUTH: ${{ secrets.KEYSTORE }}
        run: echo $AUTH | base64 --decode > /tmp/keystore

      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Bundler cache
        uses: actions/cache@v1
        with:
          path: $CACHE_BUNDLER
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Run fastlane, pull_request lane, dev configuration
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: code_analysis
          options: '{ "conf": "develop" }'
          skip-tracking: false
          subdirectory: fastlane
          bundle-install-path: CACHE_BUNDLER
        env:
          APPCENTER_API_TOKEN:     ${{ secrets.APPCENTER_API_TOKEN }}
          APPCENTER_OWNER_NAME:    ${{ secrets.APPCENTER_OWNER_NAME }}

          APP_SIGN_KEY_ALIAS:      ${{ secrets.APP_SIGN_KEY_ALIAS }}
          APP_SIGN_KEY_PASSWORD:   ${{ secrets.APP_SIGN_KEY_PASSWORD }}
          APP_SIGN_STORE_PASSWORD: ${{ secrets.APP_SIGN_STORE_PASSWORD }}

          APP_BUILD_NUMBER:        ${{ env.GITHUB_RUN_ID }}
          SONAR_TOKEN:             ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN:            ${{ secrets.GITHUB_TOKEN }}

          BAAS_BB_ARTIFACTORY_ANDROID_USERNAME:     ${{ secrets.BAAS_BB_ARTIFACTORY_ANDROID_USERNAME }}
          BAAS_BB_ARTIFACTORY_ANDROID_PASSWORD:     ${{ secrets.BAAS_BB_ARTIFACTORY_ANDROID_PASSWORD }}

