name: "UI Tests (Manual Trigger)"

#   IMPORTANT TO KNOW
#
# - This workflow can be triggered manually to run existing ui tests on any chosen branch.

on:
  workflow_dispatch:
    inputs:
      api:
        description: 'API (27 - 30)'
        required: true
        default: '30'
      emulator:
        description: 'Emulator (pixel, pixel_xl)'
        required: true
        default: 'pixel_xl'
      test_suite:
        description: 'Test suite (Smoke, Regression) or fully qualified name for test class or single test - com.class.path.className#testName'
        required: true
        default: 'Smoke'
      env:
        description: 'Environment on which tests will be executed (develop or prod)'
        required: true
        default: 'develop'

env:
  APP_SIGN_KEYSTORE_PATH: /tmp/keystore
  CACHE_BUNDLER: ~/.bundler

jobs:
  build:
    name: "${{ github.event.inputs.env }}, ${{ github.event.inputs.emulator }}, ${{ github.event.inputs.api }}, ${{ github.event.inputs.test_suite }}"
    runs-on: macos-latest
    timeout-minutes: 90

    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          secret_keystore: ${{ secrets.KEYSTORE }}

      - name: AVD Cache
        uses: ./.github/actions/avd-cache
        with:
          matrix_api: ${{ github.event.inputs.api }}
          matrix_emulator: ${{ github.event.inputs.emulator }}

      - name: Run UI Tests and publish jUnit report
        uses: ./.github/actions/ui-tests
        with:
          matrix_api: ${{ github.event.inputs.api }}
          matrix_emulator: ${{ github.event.inputs.emulator }}
          matrix_test_suite: ${{ github.event.inputs.test_suite }}
          matrix_env: ${{ github.event.inputs.env }}
          app_sign_key_alias: ${{ secrets.APP_SIGN_KEY_ALIAS }}
          app_sign_key_password: ${{ secrets.APP_SIGN_KEY_PASSWORD }}
          app_sign_store_password: ${{ secrets.APP_SIGN_STORE_PASSWORD }}
          github_run_id: ${{ env.GITHUB_RUN_ID }}
          baas_bb_artifactory_android_username: ${{ secrets.BAAS_BB_ARTIFACTORY_ANDROID_USERNAME }}
          baas_bb_artifactory_android_password: ${{ secrets.BAAS_BB_ARTIFACTORY_ANDROID_PASSWORD }}
          cache_bundler: ${{ env.CACHE_BUNDLER }}
