name: "UI Tests (Smoke)"

on:
  push:
    branches: [ develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
env:
  APP_SIGN_KEYSTORE_PATH: /tmp/keystore
  CACHE_BUNDLER: ~/.bundler

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 45

    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        api: [ 30 ]
        test_suite: [ Smoke ]
        emulator: [ pixel_xl ]
        env: [ develop ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          secret_keystore: ${{ secrets.KEYSTORE }}

      - name: AVD Cache
        uses: ./.github/actions/avd-cache
        with:
          matrix_api: ${{ matrix.api }}
          matrix_emulator: ${{ matrix.emulator }}

      - name: Run UI Tests and publish jUnit report
        uses: ./.github/actions/ui-tests
        with:
          matrix_api: ${{ matrix.api }}
          matrix_emulator: ${{ matrix.emulator }}
          matrix_test_suite: ${{ matrix.test_suite }}
          matrix_env: ${{ matrix.env }}
          app_sign_key_alias: ${{ secrets.APP_SIGN_KEY_ALIAS }}
          app_sign_key_password: ${{ secrets.APP_SIGN_KEY_PASSWORD }}
          app_sign_store_password: ${{ secrets.APP_SIGN_STORE_PASSWORD }}
          github_run_id: ${{ env.GITHUB_RUN_ID }}
          baas_bb_artifactory_android_username: ${{ secrets.BAAS_BB_ARTIFACTORY_ANDROID_USERNAME }}
          baas_bb_artifactory_android_password: ${{ secrets.BAAS_BB_ARTIFACTORY_ANDROID_PASSWORD }}
          cache_bundler: ${{ env.CACHE_BUNDLER }}
