name: "UI Tests (Full Regression Suite) Scheduled Run"

#on:
  #  https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
  #  Scheduled workflows run on the latest commit on the default or base branch - develop in our case
  #schedule:
    #- cron: '0 4 * * 1-5'

env:
  APP_SIGN_KEYSTORE_PATH: /tmp/keystore
  CACHE_BUNDLER: ~/.bundler

jobs:
  check_if_new_commits:
    name: Check if develop branch changed since last regression run
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout develop for scheduled run
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Create cache file
        run: |
          echo "$(git rev-parse HEAD)"
          echo "$(git rev-parse HEAD)" > github-sha.txt

      - name: Prepare commit sha
        id: commit_sha
        run: echo "::set-output name=value::$(git rev-parse HEAD)"

      - name: Check SHA
        id: check_sha
        uses: actions/cache@v2
        with:
          path: check-SHA
          key: check-SHA-${{ steps.commit_sha.outputs.value }}

      - name: Cancel job if cache hit didn't occur
        if: steps.check_sha.outputs.cache-hit == 'true'
        uses: andymckay/cancel-action@0.2

  build:
    runs-on: macos-latest
    timeout-minutes: 90
    needs: check_if_new_commits
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        api: [ 30 ]
        test_suite: [ Regression ]
        emulator: [ pixel_xl ]
        env: [ develop ]

    steps:
      - name: Checkout develop for scheduled run
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          secret_keystore: ${{ secrets.KEYSTORE }}
          matrix_api: ${{ matrix.api }}
          matrix_emulator: ${{ matrix.emulator }}

      - name: AVD Cache
        uses: ./.github/actions/avd-cache
        with:
          matrix_api: ${{ matrix.api }}
          matrix_emulator: ${{ matrix.emulator }}

      - name: Run UI Tests and publish jUnit report
        uses: ./.github/actions/ui-tests
        with:
          matrix_api: ${{ matrix.api }}
          matrix_emulator: ${{ matrix.emulator }}
          matrix_test_suite: ${{ matrix.test_suite }}
          matrix_env: ${{ matrix.env }}
          app_sign_key_alias: ${{ secrets.APP_SIGN_KEY_ALIAS }}
          app_sign_key_password: ${{ secrets.APP_SIGN_KEY_PASSWORD }}
          app_sign_store_password: ${{ secrets.APP_SIGN_STORE_PASSWORD }}
          github_run_id: ${{ env.GITHUB_RUN_ID }}
          baas_bb_artifactory_android_username: ${{ secrets.BAAS_BB_ARTIFACTORY_ANDROID_USERNAME }}
          baas_bb_artifactory_android_password: ${{ secrets.BAAS_BB_ARTIFACTORY_ANDROID_PASSWORD }}
          cache_bundler: ${{ env.CACHE_BUNDLER }}
